### ISSUE TITLE
Question - trying to build in VC++ v16.7.7 v3.0.8120.3593 Git-994bb08e received an error message already when building x86. Did I understand correctly that in this case you need to update the compiler to v16.8.1?

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#738]
When trying to build in VC++ v16.7.7 v3.0.8120.3593 Git-994bb08e received an error message already when building x86:

[ERROR] (1) LIB: fatal error C1900: IL mismatch between "P1" version "20200803" and "P2" version "20190715" [. \Phlib\phlib.vcxproj]
LINK: fatal error LNK1257: failed to generate code [.\Phlib\phlib.vcxproj]

Did I understand correctly that in this case you need to update the compiler to v16.8.1? And then I'm afraid that fresh errors will come out in it ...

**Comment by VictorVG** [comment]
After updating the compiler, PH got together, I check the rest - I'm afraid that there may be problems with linking in SumatraPDF and Rufus - assembly scripts are also used there ...

**Comment by dmex** [comment]
> Did I understand correctly that in this case you need to update the compiler to v16.8.1?

You can recompile \tools\thirdparty\thirdparty.sln or upgrade visual studio.

**Comment by VictorVG** [comment]
I upgrade MSVS up to v16.8.1, but have slow compile speed - v16.7.7 compile time ~ 1 min 39 sec, v16.8.1 compile time ~ 3 min 21 sec in some system:

![1](https://user-images.githubusercontent.com/906886/99515706-5aceb580-299e-11eb-9ce6-be6e4620e71e.png)

In to MS TechNet have question [**Visual Studio 2019 version 16.8.0 very slow to build. VBCSCompiler stuck? Previous version fine with same solution.**](https://developercommunity.visualstudio.com/idea/1257548/visual-studio-2019-version-1680-very-slow-to-build.html#) and according to the description of the [**Migrations Overview**](https://docs.microsoft.com/ru-ru/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli), it turns out that the new compiler checks the probability of data loss each time before performing the operation. Maybe you should think about how to eliminate these delays, for example, by writing CustomBuildTools not in .NET, but in C/C++ or use simple scripts build system exluded .NET?

**Comment by dmex** [comment]
> VBCSCompiler

We don't use the VB and C# compilers.

> Maybe you should think about how to eliminate these delays

Those bug reports are for MSBuild included with Visual Studio which is not the same as our CustomBuildTool which only launches MSBuild.

> writing CustomBuildTools not in .NET, but in C/C++ or use simple scripts build system exluded .NET?

The project is AOT compiled and rewriting the entire thing won't solve the issue with MSBuild.

**Comment by VictorVG** [comment]
Got it. The only thing that I have not yet figured out is how to roll back the compiler on the server without breaking the entire build system, but for now I have to endure these arts of "students" from M$ ...
